= Publishing Process
:toc:

// A lot of this was copied from https://wiki.apache.org/lucene-java/ReleaseTodo#Website_.2B-.3D_javadocs. See that section for explanations for why some steps are required.

== Publishing HTML Version
The steps to publish the Guide differ depending on if it is the first time the Guide has been published or if it is an update to an already published Guide.

=== Publish a New Guide

==== Step 1: Update extpaths.txt in CMS Staging

. Checkout CMS trunk: `svn co --depth=immediates https://svn.apache.org/repos/asf/lucene/cms/trunk/content website-source` ('content' is a very generic name. So, we check it out to a self-explanatory name such as 'website-source')
* If you already have this repo checked out, you can simply do `svn up` to update to the latest revision.
. `cd website-source`
. Add Guide branch dir: `echo solr/guide/X_Y_Z >> extpaths.txt`
. Commit changes `svn commit -m "Update CMS production sync exceptions for X_Y_Z Guide" extpaths.txt`


==== Step 2: Push Guide to Website Production

Go to the checkout directory where you have built the Guide and push the documentation via subversion import. You must push it to the path you just added to `extpaths.txt`, so if the path you added was `solr/guide/6.5`, you'll use the path as shown in the below example:

`svn -m "Add Ref Guide for Solr 6.5" import <checkoutroot>/solr/build/solr-ref-guide/html-site https://svn.apache.org/repos/infra/websites/production/lucene/content/solr/guide/6_5`

Confirm you can browse to these URLs manually, and especially that solr javadocs link back to lucene's correctly. Example:
https://lucene.apache.org/solr/guide/6_5

==== Step 3: Push Staging extpaths.txt to Production

The `extpaths.txt` works by listing paths that should be ignored when the CMS syncs the staging and production repositories. Publishing staging to production will only succeed if the paths listed in `extpaths.txt` exist in production. At the same time, if a path exists in production but not in staging it will be deleted unless it is defined in `extpaths.txt`. After pushing the content to production, check that the `extpaths.txt` in production includes the proper path to ensure that the Guide is not deleted incorrectly. If it does not exist in production, try to publish the site again to make sure it is updated.

Production URL: https://lucene.apache.org/extpaths.txt

==== Update Ref Guide Landing Page

Update the landing page at https://lucene.apache.org/solr/guide to link to the newest version.

You can use the CMS system for this since it is a small change, or you can edit the file locally and commit it to the staging repo.

=== Update a Published Guide

If you need to re-publish an existing online copy of the Guide, you will need to checkout the production website repository and use `svn add` and `svn commit` to overwrite the existing files:

. Chekcout the production repo: `svn co https://svn.apache.org/repos/infra/websites/production/lucene/content`
. Copy the files from the build location to the correct sub-directory under `solr/guide`. For example, if we needed to replace the current Guide for Solr 6.5, we'd do `cp -r <checkoutroot>solr/build/html-site solr/guide/6_5`
. Add the files: `svn add`
. Commit the changes: `svn commit -m "Update production 6.5 Ref Guide"`

// TODO:
// - figure out if redirects in .htaccess require any work here (probably)
